version: '3'
volumes:
  elk:
services:
    http-app:
        image: kennethreitz/httpbin
        environment:
            - "GUNICORN_CMD_ARGS=\"--capture-output --error-logfile - --access-logfile - --access-logformat \"%(h)s %(t)s %(r)s %(s)s Host: %({Host}i)s}\"\""
        ports:
        - "8080:80"
    nginx:
        image: app-protect:latest
        volumes:
            - ./logprofiles/:/etc/nginx/logprofiles/
            - ./policies/:/etc/nginx/policies/
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "8000:8000" # HTTP App (protection ON)
            - "8001:8001" # HTTP App (protection OFF)
    elasticsearch:
        image: sebp/elk:793
        restart: always
        volumes:
            - ./logstash/conf.d:/etc/logstash/conf.d
            - elk:/var/lib/elasticsearch
        ports:
            - 9200:9200
            - 5601:5601
            - 5144:5144

